language: go

go:
  - "1.6.x"  # ubuntu 16.04
  - "1.7.x"  # debian stable
  - "1.10.x" # ubuntu 18.04
  - "1.x"    # latest release

addons:
  apt:
    packages:
      - xdg-user-dirs

before_script:
  - xdg-user-dirs-update
  - mkdir -p "$HOME/.local/share/Trash/files"
  - touch "$HOME/.local/share/Trash/files/file.txt"
  - mkdir -p "$HOME/.local/share/Trash/info"
  - printf '[Trash Info]\nPath=%s\nDeletionDate=%s\n' "$HOME/file.txt" "$(date '+%Y-%m-%dT%H:%M:%S')" >"$HOME/.local/share/Trash/info/file.txt.trashinfo"

script:
  - go test -cover ./...
